github:
  description: "Apache Iggy (Incubating) Website"
  homepage: https://iggy.apache.org/
  labels:
    - rust
    - message-streaming
    - iggy
    - apache
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false

publish:
  whoami: asf-site

notifications:
  commits: commits@iggy.apache.org
  issues: commits@iggy.apache.org
  pullrequests: commits@iggy.apache.org
  discussions: dev@iggy.apache.org
