github:
  description: "Apache Iggy (Incubating) Website"
  homepage: https://iggy.apache.org/
  labels:
    - rust
    - message-streaming
    - iggy
    - apache
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false

collaborators:
  - username: landingpro
    permission: write
  
# Staging and publishing profile:
staging:
  profile: ~
  whoami: asf-staged-site

publish:
  whoami: asf-site

notifications:
  commits: commits@iggy.apache.org
  issues: dev@iggy.apache.org
  pullrequests: dev@iggy.apache.org
  discussions: dev@iggy.apache.org